template = "https://github.com/giellalt/template-lang-und"
rev_id = 127
template_sha = "bd9c999e4f6387b8963edba0b7bc664a796083ef"

[replacements]
__REPO__ = "lang-spa-x-ext-apertium"
__UND2C__ = "es"
__UNDEFINED__ = "Spanish"
__UND__ = "spa"
