template = "https://github.com/giellalt/template-lang-und"
rev_id = 96
template_sha = "f16fb241bb0ab764428c04a3c8ea25d324c6b5cd"

[replacements]
__REPO__ = "lang-spa-x-ext-apertium"
__UND2C__ = "es"
__UNDEFINED__ = "Spanish"
__UND__ = "spa"
