template = "https://github.com/giellalt/template-lang-und"
rev_id = 14
template_sha = "76687ec22319907df8c2118f1772f472ad3a249a"

[replacements]
__UND2C__ = "es"
__UNDEFINED__ = "Spanish"
__UND__ = "spa"
