template = "https://github.com/giellalt/template-lang-und"
rev_id = 104
template_sha = "dbed22967239522b32dd8b46bcf744d91eb00a16"

[replacements]
__REPO__ = "lang-spa-x-ext-apertium"
__UND2C__ = "es"
__UNDEFINED__ = "Spanish"
__UND__ = "spa"
