template = "https://github.com/giellalt/template-lang-und"
rev_id = 186
template_sha = "0fe92558ae2a50b1445da2cbe32fb65cc2359499"

[replacements]
__REPO__ = "lang-spa-x-ext-apertium"
__UND2C__ = "es"
__UNDEFINED__ = "Spanish"
__UND__ = "spa"
