template = "https://github.com/giellalt/template-lang-und"
rev_id = 155
template_sha = "dd39ceb9fcafdec1599cab355e86842f3f917fd7"

[replacements]
__REPO__ = "lang-spa-x-ext-apertium"
__UND2C__ = "es"
__UNDEFINED__ = "Spanish"
__UND__ = "spa"
